export const __esModule: true;
export const container: string;
export const endpointTypeContainer: string;
export const endpoint: string;
export const endpointUrl: string;
export const fetchBtn: string;
export const closeBtn: string;
export const loader: string;
export const spinner: string;
