export const __esModule: true;
export const container: string;
export const endpointTypeContainer: string;
export const endpoint: string;
export const endpointUrl: string;
export const fetchButton: string;
export const closeButton: string;
export const loader: string;
export const spinner: string;
